### ISSUE TITLE
Finish disturbance module, part 1.

### ISSUE THREAD

**Issue by tobeycarman** [ua-snap/dvm-dos-tem#119]
Create get some real data for the input fire files. Also figure out when/where where to read these into the model.

Basically need to fill the `Cohort::fire_years` and `Cohort::fire_sizes` vectors with data from the files. The complication comes from the fact that in `eq` and `sp` stage, the model should use "Fire Recurrence Interval" (FRI), while in the other run-stages, the model should use explicit fire year. It seems like there are a few approaches to handling this:
1. Pre-calculate explicit fire year (based on some rule for FRI, likely with python as a pre-processing step) and use that to fill the input (netcdf) fire file.
2. Detect the stage at model run-time and fill the internal fire_year vector accordingly.
3. Use fire year vector (loaded from input files), but in `eq` and `sp` use an FRI variable that is set from somewhere...where?

**Comment by rarutter** [comment]
Temporary branch salvage_dsb_branch contains many of the changes in iss119-fire-dsb-module, rebased onto devel.

Below is a list of commits from the old branch, a basic category, and whether or not they were included in the rebase. Some of the util commits were not included as they had already been re-implemented on devel.

This is incomplete - more details later.

SHA | Category | Rebased?
--- | --- | ---
6f0059 | fire | yes
091542 | util | no
abedb0 | bug | separate
06b344 | util | no
1f5a6d | testing | no
23b3b0 | fire, util | partial
fb799c | fire, cleanup |
8f06e8 | fire | yes
53092d | input | yes
466e95 | util | 
994d49 | util | yes
8c3646 | refac | no
7ee0ab | ws/comments | later
99d119 | ws/formatting | later
27ad16 | ws/formatting | later
9005b0 | util | no
8f47a3 | input, fire | yes
390721 | input | yes
019ddb | ws/comments | yes
7b5c99 | fire | yes
b1da09 | fire | yes
45ddfa | fire | yes
8da442 | ws/comments | yes
94a581 | ws/comments | yes
379772 | fire | yes
022d84 | fire comments | yes
4b05ff | fire | yes
e557b2 | ws/comments | yes
f72a8a | util | later
b8ecc5 | fire | most
5e57f8 | ground | no
e773d7 | ws ground | no
45988d | ws/comments | no
0b914f | input | yes
4dd879 | ws/comments | yes
d83c32 | fire | yes
61ca66 | wc/omments |  no
774004 | util, comments | yes
2d4e51 | input | in progress
6067ca | fire | in progress

**Comment by rarutter** [comment]
Working with Helene on diagnosing the fire module errors.

Examining the Ground report layers:
1. Dead moss C is not reported correctly in the outputs.
2. OL thickness used to compute burn thickness is wrong - shouldn't take green moss layer into account as it does not carry advantageous roots.
3. Temperature is not recovering correctly, but z is correct
4. DOB is wrong (year is correct)
5. RH=0 when tdeep>0

By examining the RawC and other values in Soil_Bgc::deltac, we see that rhmoist is 0.

**Comment by rarutter** [comment]
Resolved by PRs #224 #231 #234 #243
