### ISSUE TITLE
Add capability for projected climate info (enables stage transitions)

### ISSUE THREAD

**Issue by tobeycarman** [ua-snap/dvm-dos-tem#121]
Haven't finished handling both historic and projected climate drivers yet. Since it is possible to run the `eq` stage with just the historic data, things are hardcoded to use historic right now (See Cohort constructor). 

Solving this issue will involve making some decisions about how/when to read in historic vs projected data and also how to decide which to use (maybe somewhere in the vicinity of the `BOOST_LOG_NAMED_SCOPE`s for selecting stages in `TEM.cpp`

**Comment by tobeycarman** [comment]
I think this is finished now?

**Comment by rarutter** [comment]
This seems to be resolved by PR #157
