### ISSUE TITLE
Input generation: handle unequal year values

### ISSUE THREAD

**Issue by rarutter** [ua-snap/dvm-dos-tem#154]
For a full input set, historic and projected climate year values are not the same. Currently historic is 109 and projected is 100. The 'all' option will fix that for now, but we should add proper validation and error messages.

**Comment by tobeycarman** [comment]
Ha, I just ran into this problem yesterday. I did not use the 'all' option. Will try it again.

**Comment by rarutter** [comment]
The 'all' options is unfortunately only partially functional. I will push a fix for that shortly.

**Comment by tobeycarman** [comment]
closed by merging pull request #203.
