### ISSUE TITLE
consolidate "post warm up pause" with "inter stage pause" configuration options.

### ISSUE THREAD

**Issue by tobeycarman** [ua-snap/dvm-dos-tem#210]
The "pwup" (post warm up pause) option is set in the calibration_directives.txt file, and the "inter_stage_pause" is set in the config.js file. 

Seems like we should be able to abandon the "post warm up pause" option and get that functionality by looking at the inter_stage_pause option?

**Comment by rarutter** [comment]
I don't know of a situation where we would want to look at the warm up data and not pause between the other stages. Even if there was one, it's a good idea to have all the 'pause' controls in one place.
