### ISSUE TITLE
Diagnose and repair soil problems post fire

### ISSUE THREAD

**Issue by rarutter** [ua-snap/dvm-dos-tem#225]
Dvmdostem compiles and runs with the fire module added. It burns, but there are a few problems with it. VegC does not recover post-fire, RH is zero, and soil temperature recovers very slowly. This shows carbon non-recovery:
<img width="1064" alt="allmodules_pft2_vegsoil" src="https://cloud.githubusercontent.com/assets/6707880/18971283/082e593e-8641-11e6-8841-860229bee845.jpg">

**Comment by rarutter** [comment]
Working with Helene on diagnosing the fire module errors.

Examining the Ground report layers:
1. Dead moss C is not reported correctly in the outputs.
2. OL thickness used to compute burn thickness is wrong - shouldn't take green moss layer into account as it does not carry advantageous roots.
3. Temperature is not recovering correctly, but z is correct
4. DOB is wrong (year is correct)
5. RH=0 when tdeep>0

By examining the RawC and other values in Soil_Bgc::deltac, we see that rhmoist is 0.
The tmp_sois.rawc post fire has increased more than the carbon from vegetation burning would explain (maybe - checking...). This is not the case. Remember that layer numbering changes during a fire.

**Comment by rarutter** [comment]
Integrator.cpp:613. The month after fire we have no moss layers (rawc values will support this). However, there are deltas written out to del_sois...

**Comment by rarutter** [comment]
Soil_Bgc.cpp:1022.
```c++
if (tmp_sois.dmossc) > 0.) {
  del_sois.dmossn = mossdeathn;
  del_sois.dmossn -= del_soi2a.rhmossc * tmp_sois.dmossn / tmp_sois.dmossc;
}
```
In the month post fire (and beyond), dmossc is equal to zero, so this if statement is bypassed. In this case, dmossn retains the value it held the prior month. This is incorrect and 'del' structs should be zeroed directly before integration (just prior to adapt() calls, probably).

**Comment by rarutter** [comment]
With del structs zeroed, moss layers are correctly inserted at the top of the soil stack at the beginning of the year following fire (if there is dead moss carbon). This isn't quite correct - they should appear as soon as there is deadmossc, but this is progress. The fstsoill pointer is not correctly updated, however. `insertBefore()` has probably only been used for snow before, so it was never an issue.

**Comment by hgenet** [comment]
Nice Ruth!!! I'm glad that this trial worked out well! We may want to 
try this for the shallow layer as well.

Let's talk about it this aftrenoon.

----
Hélène Genet, PhD
Institute of Arctic Biology
University of Alaska Fairbanks
902 Koyukuk Drive
Fairbanks, AK 99775 - USA
Phone: +1 907 699 4340
Email: hgenet@alaska.edu
Skype: helenegenet
