### ISSUE TITLE
Figure out how to handle "no data" pixels.

### ISSUE THREAD

**Issue by tobeycarman** [ua-snap/dvm-dos-tem#276]
What should the behavior be when the model encounters a pixel for which there is limited or no data (for example ocean or lake pixels, or high mountains with no community type)?. Ideally all of our input datasets will be perfectly aligned, but I have not verified this and we might not be able to count on it.

One idea is to have a pre-processing step that looks at all pixels in the input domain, and if any of the inputs are missing or are "no data" pixels, then set the run-mask to `0` for that pixel.

Alternatively this could be handled internally in the model  (C++ code).

**Comment by rarutter** [comment]
For some discussion see Helene's email from 6/28.

**Comment by tobeycarman** [comment]
Addressed by #303, #304 , and #305. General strategy has been to handle this with pre-processing. The python scripts look thru all the input data and mask off any pixels where there is insufficient input data.
