### ISSUE TITLE
Implement OpenMP

### ISSUE THREAD

**Issue by rarutter** [ua-snap/dvm-dos-tem#289]
Reorganize run_mask? Check timing...
Ensure openmp is only linked if the user specifies it (see MPI)
Diagnose error on input file access
Lock individual output file accesses
Profile

Timing
SHA 459d09, 2x2 cells (first two in rows and columns)
PR 10, EQ 500, SP 100, TR 100
No monthly outputs, no EQ output
W/o OMP: 614 seconds
W/ OMP: 

Future possibilities
Re-evaluate possible parallel I/O with HDF5? This would require the parallel-enabled build of NetCDF. I recall having issues with it when we tried before.

Done
Implement single loop openmp
Either flatten loop structure or parallelize second loop. Currently using _collapse()_
Update Makefile
Update SConstruct
Lock input file accesses
Lock output file accesses (entire function)

**Comment by tobeycarman** [comment]
So am I thinking about this correctly (probably not):

 - There will be one OpenMP thread for each grid cell to be run (or each row or column if only one loop is parallelized)
 - The maximum number of threads it will be advantageous to have per node on Atlas is equal to the number of cores per node. In other words the goal is to have a single thread running on a single core executing a single grid cell.
- A pre-processing step will be to take the input domain and split it into chunks where each chunk will fit on an atlas node. So if AtlasNode 1 has 64 cores, then we will want Node1 to receive the inputs for 64 grid cells.
- We could transfer a copy of the entire input domain onto each node on Atlas and then modify the run mask appropriately for each node OR we could actually subset the input domain and only transfer the smaller input files to each Atlas node.

**Comment by rarutter** [comment]
- Yes (as I have it set up right now, one thread per cell)
- Since I believe we aren't expecting an enormous disparity between runtimes per thread, this is the case. If we expected any threads to 'lap' the others, this might not be true. (This should be tested when we can...)
- This should be a balance between core count and data size. As long as the data size is reasonable, then yes we would want to send each node a data set such that the number of cells is a multiple of the number of cores. Right now, this is complicated by the fact that we need to keep the data slicing and merging simple, which is easier to do based on chunking the data into rectangles, which then may not have anything to do with the number of cores. Accepting that not all cores will be used at all times may be necessary, but we don't want to end up with a setup where only a few threads are doing an entire run for their cells.
- True, but given that the size of the input domain can vary wildly from run to run (up to the entire AIEM domain, which is a lot of data), it would be good to have a scalable way to control how much data is transferred to each node. I think this leads into wanting to subset the input sets per node.

**Comment by tobeycarman** [comment]
OK, great, that helps a bunch.

**Comment by rarutter** [comment]
Resolved by PR #300
