### ISSUE TITLE
Implement parallel IO for the restart files

### ISSUE THREAD

**Issue by rarutter** [ua-snap/dvm-dos-tem#337]
Duh

**Comment by rarutter** [comment]
Currently the 337_parallelize_restart_output branch successfully writes parallel restart files, so long as the number of processes is a factor of the total number of cells.

**Comment by tobeycarman** [comment]
So is the next priority then allowing the model to start from an arbitrary restart file?? (maybe specified from command line)?

**Comment by rarutter** [comment]
Well, first I'm trying to fix the part where it hangs if the number of processes is not a factor of the total cell count. But yes, being able to start from a restart file is after that. Although that is something that could be worked on while a run is going.

**Comment by tobeycarman** [comment]
OK, good point re: being able to address that while a run is going.

For future reference, it looks like we have stubs in place for starting from a restartData file. In Cohort.cpp, there is a `void Cohort::set_restartdata_from_state()` function (that is working I believe) and then the skeleton on `void Cohort::set_state_from_restartdata()`.

**Comment by rarutter** [comment]
Fixed by PR #354
