### ISSUE TITLE
Compile on vagrant using scons

### ISSUE THREAD

**Issue by hgenet** [ua-snap/dvm-dos-tem#341]
This is the error message I get when I try to compile a freshly cloned version of dvm-dos-tem on vagrant using scons -j4.
Any idea?

scons: Reading SConscript files ...
/usr/bin/g++
/usr/lib64/openmpi/bin/mpic++
Compiler: /usr/lib64/openmpi/bin/mpic++
scons: done reading SConscript files.
scons: Building targets ...
/usr/lib64/openmpi/bin/mpic++ -o src/TEM.o -c -Wno-error -ansi -g -fPIC -DBOOST_ALL_DYN_LINK -DGNU_FPE -m64 -DWITHMPI -DGIT_SHA=\"59ab18\" -I/home/UA/rarutter/downloads/hdf5-1.8.19/hdf5/include -I/home/UA/rarutter/downloads/netcdf-4.4.1.1/netcdf/include -I/usr/include -I/usr/include/openmpi-x86_64 -I/usr/include/jsoncpp -I/home/vagrant/netcdf-4.4.1.1/netcdf/include -I~/usr/local/include src/TEM.cpp
/usr/lib64/openmpi/bin/mpic++ -o src/OutputEstimate.o -c -Wno-error -ansi -g -fPIC -DBOOST_ALL_DYN_LINK -DGNU_FPE -m64 -DWITHMPI -DGIT_SHA=\"59ab18\" -I/home/UA/rarutter/downloads/hdf5-1.8.19/hdf5/include -I/home/UA/rarutter/downloads/netcdf-4.4.1.1/netcdf/include -I/usr/include -I/usr/include/openmpi-x86_64 -I/usr/include/jsoncpp -I/home/vagrant/netcdf-4.4.1.1/netcdf/include -I~/usr/local/include src/OutputEstimate.cpp
/usr/lib64/openmpi/bin/mpic++ -o src/CalController.o -c -Wno-error -ansi -g -fPIC -DBOOST_ALL_DYN_LINK -DGNU_FPE -m64 -DWITHMPI -DGIT_SHA=\"59ab18\" -I/home/UA/rarutter/downloads/hdf5-1.8.19/hdf5/include -I/home/UA/rarutter/downloads/netcdf-4.4.1.1/netcdf/include -I/usr/include -I/usr/include/openmpi-x86_64 -I/usr/include/jsoncpp -I/home/vagrant/netcdf-4.4.1.1/netcdf/include -I~/usr/local/include src/CalController.cpp
In file included from src/../include/OutputEstimate.h:20:0,
                 from src/OutputEstimate.cpp:12:
src/../include/ModelData.h:17:24: fatal error: netcdf_par.h: No such file or directory
 #include <netcdf_par.h>
                        ^
compilation terminated.
In file included from src/../include/../src/runmodule/../ecodomain/../data/CohortData.h:13:0,
                 from src/../include/../src/runmodule/../ecodomain/../data/EnvData.h:17,
                 from src/../include/../src/runmodule/../ecodomain/../data/BgcData.h:17,
                 from src/../include/../src/runmodule/../ecodomain/Ground.h:27,
                 from src/../include/../src/runmodule/Cohort.h:6,
                 from src/../include/CalController.h:17,
                 from src/CalController.cpp:13:
src/../include/../src/runmodule/../ecodomain/../data/../../include/ModelData.h:17:24: fatal error: netcdf_par.h: No such file or directory
 #include <netcdf_par.h>
                        ^
compilation terminated.
In file included from src/../include/OutputEstimate.h:20:0,
                 from src/TEM.cpp:72:
src/../include/ModelData.h:17:24: fatal error: netcdf_par.h: No such file or directory
 #include <netcdf_par.h>
                        ^
compilation terminated.
/usr/lib64/openmpi/bin/mpic++ -o src/ArgHandler.o -c -Wno-error -ansi -g -fPIC -DBOOST_ALL_DYN_LINK -DGNU_FPE -m64 -DWITHMPI -DGIT_SHA=\"59ab18\" -I/home/UA/rarutter/downloads/hdf5-1.8.19/hdf5/include -I/home/UA/rarutter/downloads/netcdf-4.4.1.1/netcdf/include -I/usr/include -I/usr/include/openmpi-x86_64 -I/usr/include/jsoncpp -I/home/vagrant/netcdf-4.4.1.1/netcdf/include -I~/usr/local/include src/ArgHandler.cpp
scons: *** [src/OutputEstimate.o] Error 1
scons: *** [src/CalController.o] Error 1
scons: *** [src/TEM.o] Error 1
scons: building terminated because of errors.

**Comment by tobeycarman** [comment]
We accidentally let the default setting change in the main repo. Try changing to `USEMPI = False` in either the Makefile or the SConstruct file (depending on which file you are using for building).
