### ISSUE TITLE
LAI outputs are unreasonably static

### ISSUE THREAD

**Issue by tobeycarman** [ua-snap/dvm-dos-tem#382]
LAI values being output seem to be constant annually and the monthly pattern seems to be the same across all years. Also the values should be between 0 and 1 (maybe >1?)

![screen shot 2018-07-12 at 10 56 13 am](https://user-images.githubusercontent.com/838735/42653605-5960c88c-85c2-11e8-9194-bc209c2184ac.png)

```
import netCDF4 as nc
import os
import matplotlib.pyplot as plt
od = 'input-staging-area/site_4_1x1/output/'
lai = nc.Dataset(os.path.join(od, "LAI_monthly_tr.nc"))
plt.plot(lai.variables['LAI'][0:120,0,0])
plt.ticklabel_format(useOffset=False)
plt.draw()
```

Plot from a run done on Altas, Dalton Highway site 4.

**Comment by tobeycarman** [comment]
@rarutter, @hgenet might the fix that you recently pulled into devel (#381 ) fix this??

**Comment by rarutter** [comment]
Given the values in that plot, I suspect it does. I'll take a look at it in
a little bit.

**Comment by tobeycarman** [comment]
This seems fixed as of 1/2/2018. Maybe aided by #401. 

Here is output LAI from sha: 34496a9345ff5c3e1252d9037f3e7e2663bbef57.

Modified output spec to turn on all LAI outputs and then run with:
```
./dvmdostem -l warn -p 5 -e 100 -s 50 -t 115 -n 85
```
Then plot:
```
vagrant@vagrant:~/dvm-dos-tem (master)$ ./scripts/plot_output_var.py --file output/LAI_monthly_sp.nc --timesteps 0 100 --annual-grid
```
![screen shot 2019-01-02 at 11 36 57 am](https://user-images.githubusercontent.com/838735/50606374-c2e78180-0e82-11e9-86c5-4863d127eb19.png)
