### ISSUE TITLE
Reformat NetCDF output.

### ISSUE THREAD

**Issue by rarutter** [ua-snap/dvm-dos-tem#44]

**Comment by rarutter** [comment]
Restarting work on defining output NetCDF files.

Helene mentioned that there is a risk of data loss when using NCOs on NetCDF files larger than 12GB (she's pretty certain of that number)

**Comment by rarutter** [comment]
Notes from working with Helene on this

Need output files from each stage. Not PR.

Dimension order. NetCDF examples tend to have time first (necessary, since it's unlimited), followed by other dimensions (in our case would be layer, pft, pftpart), and then y and x. There seems to be no specific NetCDF standard requirement for this, though, and since all variables have time,y,x, it's more logical to list those first.

Fill_Value is incredibly important! Pick something not at all feasible.
There are sometimes issues if you specify fill value and missing value and the values are not the same. Default to always specifying fill value

For some variables (e.g. soil carbon in unfrozen layers), compute on the run based on actual layer properties. Keep in mind that ALD would mess this up, as top layers may be frozen with thawed layers underneath (in the fall especially)

**Comment by tobeycarman** [comment]
re: dimension order, I agree that there is not NetCDF specific standard for
order, but the CF conventions call for (time, z, y, x), and recommend that
if there are more dimensions, they should be added to the left:
http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#dimensions

**Comment by rarutter** [comment]
Ah, so they do (of course the COARDS standards has them completely opposite...). It looks like that's because they expect longitude to be the fastest changing. No reason not to stick with that, I think. I'll get those switched around.

**Comment by hgenet** [comment]
Thanks Tobey for checking this. Having the time, y,x as first dimensions 
and the others like PFT,layer and compartment following those makes lots 
of sense.

Helene

----
Hélène Genet, PhD
Institute of Arctic Biology
University of Alaska Fairbanks
902 Koyukuk Drive
Fairbanks, AK 99775 - USA
Phone: +1 907 699 4340
Email: hgenet@alaska.edu
Skype: helenegenet

**Comment by tobeycarman** [comment]
Wait, just to make sure we are on the same page here: I am seeing both the
COARDS and CF standards calling for (time, z, y, x). The CF standards are
an extension of the COARDS standards, so I would be surprised if they
disagreed here.

CF:
http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#dimensions
COARDS: http://ferret.wrc.noaa.gov/noaa_coop/coop_cdf_profile.html

Also both standards indicate that any further dimensions should be to the
*left* of the spatiotemporal dimensions, so something like this for PFT
specific GPP:

float gpp(pft, time, y, x);

And this might be a definition for a per-pft, per compartment variable:

float VegC(compartment, pft, time, y, x);

I guess for a soil variable, we should use the depth dimension, so
something like this:

float temperature(time, depth, y, x);

Does this match what you both have been thinking, or am I reading those
documents incorrectly?

- Tobey

**Comment by rarutter** [comment]
Those examples show what I understood from the first link (cfconventions dimensions). I followed the link from there to
http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#coards-relationship
which indicates an ordering of lon, lat, vertical, and time. It does seem odd that CF and COARDS wouldn't agree, so perhaps I'm not reading it right?

**Comment by tobeycarman** [comment]
Huh, that is strange. I agree, in the link you just sent describing the relationship between COARDS and CF, it says that the old COARDS standard was "lon, lat, vertical, time", but if you go to the COARDS webpage, they specify "time, height, lat, lon"...

**Comment by tobeycarman** [comment]
Going back to one of your first comments, re: time necessarily being first due to it being unlimited, I am not really sure how to handle that in cases where we have more than 4 dimensions?? Any idea?

**Comment by hgenet** [comment]
I didn't had time to read through the documentation yet, but one thing 
we might have to consider as well is the unlimited nature of some of 
those dimensions. Unlimited dimensions need to be listed first. But the 
thing is that these unlimited dimensions might change depending on if we 
run the time loop or the space loop first...

Helene

----
Hélène Genet, PhD
Institute of Arctic Biology
University of Alaska Fairbanks
902 Koyukuk Drive
Fairbanks, AK 99775 - USA
Phone: +1 907 699 4340
Email: hgenet@alaska.edu
Skype: helenegenet

**Comment by rarutter** [comment]
Most of the points in this thread are addressed by PR #257 . The rest have been moved to Issue #258
