### ISSUE TITLE
Use Net Ecosystem Exchange (NEE) in calibration process.

### ISSUE THREAD

**Issue by tobeycarman** [ua-snap/dvm-dos-tem#504]
Add a target values for NEE to the `calibration_targets.py` and add data such that NEE can be displayed on the calibration plots.

If NEE can be made available as a json output variable then adding to the plots should be easy (add a line to the `configured_suites` data structure. Might be easy to add logic to the `Runner.cpp::output_caljson_monthly(...)` and `Runner.cpp::output_caljson_yearly(...)` functions that can sum up the various respiration fluxes to create NEE.

**Comment by tobeycarman** [comment]
@hgenet, looking [here](https://github.com/ua-snap/dvm-dos-tem/blob/d2d23e45a673bc2be552ae068c4c462eb89398cc/src/Runner.cpp#L384) are there other values that should be included in the sum for NEE:
```
 data["RHraw"] = cohort.bdall->m_soi2a.rhrawcsum;
 data["RHsoma"] = cohort.bdall->m_soi2a.rhsomasum;
 data["RHsompr"] = cohort.bdall->m_soi2a.rhsomprsum;
 data["RHsomcr"] = cohort.bdall->m_soi2a.rhsomcrsum;
 data["RHwdeb"] = cohort.bdall->m_soi2a.rhwdeb;
 data["RH"] = cohort.bdall->m_soi2a.rhtot;
 data["PFT" + pft_str]["RespGrowth"]["Leaf"] = cohort.bd[pft].m_v2a.rg[I_leaf];
 data["PFT" + pft_str]["RespGrowth"]["Stem"] = cohort.bd[pft].m_v2a.rg[I_stem];
 data["PFT" + pft_str]["RespGrowth"]["Root"] = cohort.bd[pft].m_v2a.rg[I_root];
 data["PFT" + pft_str]["RespMaint"]["Leaf"] = cohort.bd[pft].m_v2a.rm[I_leaf];
 data["PFT" + pft_str]["RespMaint"]["Stem"] = cohort.bd[pft].m_v2a.rm[I_stem];
 data["PFT" + pft_str]["RespMaint"]["Root"] = cohort.bd[pft].m_v2a.rm[I_root];
 ```

**Comment by hgenet** [comment]
Tobey, ,

I just want to make sure that we are all on the same line in terms of definition. 
NEE = net ecosystem exchange
ER = ecosystem respiration
We want to use not only NEE but also ER for calibration.

NEE = ER - GPP 

ER = RG + RM + RH

Growth and maintenance respiration (RG and RM resp.) and heterotrophic respiration (RH).

ER is the main variable I’d like to add to the calibration diagnostic. NEE would be great as well.

Cheers,

Helene 
---
Hélène GENET, Ph.D.

Assistant Professor
Institute of Arctic Biology
University of Alaska Fairbanks

A: Arctic Health Research Building, Room 128, 
Koyukuk Drive, Fairbanks AK 99775, USA 
C: +1 (907) 699 4340
E: ***@***.***

**Comment by tobeycarman** [comment]
@hgenet excellent, thanks for the clarification. So it looks like the variables I listed above should be enough to find ER? I guess we need to see if `cohort.bdall->m_soi2a.rhtot` is already a sum of `rhrawcsum`, `rhsomasum`, etc.

**Comment by tobeycarman** [comment]
Indeed, it looks like `rhtot` is already the sum of the other variables, see [here](https://github.com/ua-snap/dvm-dos-tem/blob/d2d23e45a673bc2be552ae068c4c462eb89398cc/src/BgcData.cpp#L391):
```
void BgcData::soil_endOfMonth(const int currmind) {
...
  m_soi2a.rhtot = m_soi2a.rhrawcsum +
                  m_soi2a.rhsomasum +
                  m_soi2a.rhsomprsum +
                  m_soi2a.rhsomcrsum +
                  m_soi2a.rhwdeb;
...
```
